version: '3.11.0'
services:
  db-green:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    container_name: db-green
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PW}'
      MYSQL_ROOT_PASSWORD: '${DB_PW}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    networks:
      - backend_networks
      - admin_networks
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '${DB_PORT}'
    volumes:
      - 'mysql_data:/data/mysql'
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - admin_networks
  green-app:
    container_name: green-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '${LISTEN_PORT}:${LISTEN_PORT}'
    networks:
      - backend_networks
    depends_on:
      - db-green
volumes:
  mysql_data:
    driver: local
networks:
  backend_networks:
    driver: bridge
  admin_networks:
    driver: bridge
