version: '3.11.0'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PW}'
      MYSQL_ROOT_PASSWORD: '${DB_PW}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_PASSWORD}'
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '${DB_PORT}'
    volumes:
      - 'mysql_data:/data/mysql'
    networks:
      - backend_networks
    env_file:
      - .env
  green-app:
    container_name: green-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '${LISTEN_PORT}:${LISTEN_PORT}'
    networks:
      - backend_networks
    depends_on:
      - db
networks:
  backend_networks:
    driver: bridge
    name: green-app-backend
volumes:
  mysql_data:
    driver: local

