version: 3.8.0

services:
  db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PW}'
      MYSQL_ROOT_PASSWORD: '${DB_PW}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  nestjs:
    build: .
    env_file:
      - .env
    ports:
      - '${LISTEN_PORT}:${LISTEN_PORT}'
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
