export enum TagScreenEnum {
  UI_PAGE = 'UI_PAGE',
  REGISTER_PAGE = 'REGISTER_PAGE',
  LOGIN_PAGE = 'LOGIN_PAGE',
  PROFILE_PAGE = 'PROFILE_PAGE',
  HOME_PAGE = 'HOME_PAGE',
  PAYMENT_PAGE = 'PAYMENT_PAGE',
  SETTING_PAGE = 'SETTING_PAGE',
  MESSAGE = 'MESSAGE',
}
